### ISSUE TITLE
Paradigmatic table for I: isn't working

### ISSUE THREAD

**Issue by hadware** [IEMLdev/ieml-api#4]
Je sais pas si c'est normal ou pas, mais ça fait planter le serveur, donc faut gérer ce cas là.

**Comment by plevyieml** [comment]
Pareil pour E, U, A, S, B, T, O, M, F ? (en fait, toute la couche 0?)

**Comment by hadware** [comment]
C'est normal qu'il nexiste pas de table pour les symboles primitifs non? C'est plus pour I: uniquement que c'est inquiétant.

Si Les autres termes primitifs prennent du temps à s'afficher c'est à cause d'astronomique quantité de relations pour chacun de ces termes.

**Comment by plevyieml** [comment]
Justement, il faudrait désactiver la liste des descendants pour E, U, A, S, B, T, O, M, F
